service: lastFmFriendsApi # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x

functions:
  getFriends:
    handler: handler.getFriends
    events:
      - http:
          path: api/friends/{user}
          method: get
          cors: true
          request:
              parameters:
                  paths:
                      user: true
